### ISSUE TITLE
cannot open folder on Ubuntu

### ISSUE THREAD

**Issue by megdimka** [kzahel/web-server-chrome#160]
Ubuntu 18.04 amd64
![screenshot](https://user-images.githubusercontent.com/39437446/47926297-ed3fb180-dec8-11e8-9e48-accc9f5953b3.png)
```
Unchecked runtime.lastError while running fileSystem.chooseEntry: Invalid calling page. This function can't be called from a background page.
    at HTMLElement.onChooseFolder (<URL>)
    at HTMLElement.handler (<URL>)


Unchecked runtime.lastError while running fileSystem.chooseEntry: Invalid calling page. This function can't be called from a background page.
    at HTMLElement.onChooseFolder (chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/polymer-ui/index.js:132:31)
    at HTMLElement.handler (chrome-extension://ofhbbkphhbklhfoeikjpcbhemlocgigb/polymer-ui/build.js:3344:17)
```

**Comment by kzahel** [comment]
Thanks for the bug report. I will test on linux to verify

**Comment by tamirciat** [comment]
hi,
same to me on opensuse: "choose folder" option dont work

**Comment by arunkumaraqm** [comment]
I am on Vivaldi too and I am having the same issue.

**Comment by dirk-ecker** [comment]
Me to

**Comment by kzahel** [comment]
The original Chrome App is no longer supported. The app has been rebuilt from scratch — see https://ok200.app for the new versions and to sign up for updates.
