### ISSUE TITLE
Cannot build (

### ISSUE THREAD

**Issue by xchellx** [kzahel/web-server-chrome#210]
I cannot build from babel using `npm run watch` as per build instructions.
I am running from Lubutnu (Ubuntu 18.04.4 LTS).
```
xchellx@xchellx-VirtualBox:~/Desktop/git/web-server-chrome/react-ui$ npm run watch

> @ watch /home/xchellx/Desktop/git/web-server-chrome/react-ui
> babel js --verbose --watch --out-dir nojsx --source-maps

{ SyntaxError: /home/xchellx/Desktop/git/web-server-chrome/react-ui/js/index.js: Support for the experimental syntax 'classProperties' isn't currently enabled (113:9):

  111 | 
  112 | class App extends React.Component {
> 113 |   state = {
      |         ^
  114 |     showAdvanced: false,
  115 |     interfaces: [],
  116 |     port: 6669,

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
    at Parser._raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:723:17)
    at Parser.raiseWithData (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:716:17)
    at Parser.expectPlugin (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:8615:18)
    at Parser.parseClassProperty (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11925:12)
    at Parser.pushClassProperty (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11885:30)
    at Parser.parseClassMemberWithIsStatic (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11818:14)
    at Parser.parseClassMember (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11755:10)
    at withTopicForbiddingContext (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11710:14)
    at Parser.withTopicForbiddingContext (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:10791:14)
    at Parser.parseClassBody (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:11687:10)
  loc: Position { line: 113, column: 8 },
  pos: 2592,
  missingPlugin: [ 'classProperties' ],
  code: 'BABEL_PARSE_ERROR' }
{ SyntaxError: /home/xchellx/Desktop/git/web-server-chrome/react-ui/js/options.js: Unexpected token (37:10)

  35 |       case Number: {
  36 |         return (
> 37 |           <TextField
     |           ^
  38 |             disabled={disabled}
  39 |             error={error}
  40 |             helperText={error ? meta.validationError : ''}
    at Parser._raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:723:17)
    at Parser.raiseWithData (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:716:17)
    at Parser.raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:710:17)
    at Parser.unexpected (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:8610:16)
    at Parser.parseExprAtom (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9893:20)
    at Parser.parseExprSubscripts (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9479:23)
    at Parser.parseMaybeUnary (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9459:21)
    at Parser.parseExprOps (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9329:23)
    at Parser.parseMaybeConditional (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9302:23)
    at Parser.parseMaybeAssign (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9257:21)
  loc: Position { line: 37, column: 10 },
  pos: 929,
  code: 'BABEL_PARSE_ERROR' }
Successfully compiled 0 files with Babel.
```

EDIT:
After adding the required plugin:
```
xchellx@xchellx-VirtualBox:~/Desktop/git/web-server-chrome/react-ui$ sudo npm run watch

> @ watch /home/xchellx/Desktop/git/web-server-chrome/react-ui
> babel js --verbose --watch --out-dir nojsx --source-maps

{ SyntaxError: /home/xchellx/Desktop/git/web-server-chrome/react-ui/js/index.js: Unexpected token (244:15)

  242 |           }
  243 |         }
> 244 |         return <AppOption indent={indent} disabled={!enabled} onChange={this.onChange.bind(this)} name={k} key={k} value={this.state[k]} appOptions={_this.appOptions} />
      |                ^
  245 |       })];
  246 |       return options;
  247 |     }
    at Parser._raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:723:17)
    at Parser.raiseWithData (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:716:17)
    at Parser.raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:710:17)
    at Parser.unexpected (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:8610:16)
    at Parser.parseExprAtom (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9893:20)
    at Parser.parseExprSubscripts (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9479:23)
    at Parser.parseMaybeUnary (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9459:21)
    at Parser.parseExprOps (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9329:23)
    at Parser.parseMaybeConditional (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9302:23)
    at Parser.parseMaybeAssign (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9257:21)
  loc: Position { line: 244, column: 15 },
  pos: 6289,
  code: 'BABEL_PARSE_ERROR' }
{ SyntaxError: /home/xchellx/Desktop/git/web-server-chrome/react-ui/js/options.js: Unexpected token (37:10)

  35 |       case Number: {
  36 |         return (
> 37 |           <TextField
     |           ^
  38 |             disabled={disabled}
  39 |             error={error}
  40 |             helperText={error ? meta.validationError : ''}
    at Parser._raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:723:17)
    at Parser.raiseWithData (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:716:17)
    at Parser.raise (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:710:17)
    at Parser.unexpected (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:8610:16)
    at Parser.parseExprAtom (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9893:20)
    at Parser.parseExprSubscripts (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9479:23)
    at Parser.parseMaybeUnary (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9459:21)
    at Parser.parseExprOps (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9329:23)
    at Parser.parseMaybeConditional (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9302:23)
    at Parser.parseMaybeAssign (/home/xchellx/Desktop/git/web-server-chrome/react-ui/node_modules/@babel/parser/lib/index.js:9257:21)
  loc: Position { line: 37, column: 10 },
  pos: 929,
  code: 'BABEL_PARSE_ERROR' }
Successfully compiled 0 files with Babel.
```

**Comment by kzahel** [comment]
Thanks. I forgot the babelrc. pull and try again
https://github.com/kzahel/web-server-chrome/commit/c6e9056e5f03b51621dfc608fd283d6850083d5d
